version: '3'

services:

  web:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_PORT: 3306
      PMA_HOSTS: host.docker.internal
      UPLOAD_LIMIT: 3000000000
    network_mode: host
    restart: always
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
